obstacle_range: 1.0
raytrace_range: 2.0
footprint: [[-0.097, 0.1], [0.097, 0.1], [0.097, -0.1], [-0.097, -0.1]]
#robot_radius: ir_of_robot
inflation_radius: 0.05

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}

